apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ecommdeploy
  name: ecommdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecommdeploy
    spec:
      containers:
      - image: eswaribala/rpsintelrepo:ecommapp-v1
        name: v1
        resources: {}
        env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysql:3306/ericecommdb?useSSL=false
               

status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ecommservice
  name: ecommservice
spec:
  ports:
  - name: 7076-7070
    port: 7070
    protocol: TCP
    targetPort: 7076
  selector:
    app: ecommdeploy
  type: ClusterIP
status:
  loadBalancer: {}
